import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

import { Header } from "@/components/layout/header";
import { Toaster } from "@/components/ui/sonner";
import { getAuthenticatedAppForUser } from "@/lib/firebase/server/serverApp";
import { User } from "firebase/auth";

export const dynamic = "force-dynamic"; // SSR

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const { currentUser } = await getAuthenticatedAppForUser();
  const initialUser = currentUser?.toJSON() as User;

  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div className="grid min-h-dvh grid-rows-[auto_1fr]">
          <Header initialUser={initialUser} />
          {children}
        </div>
        <Toaster />
      </body>
    </html>
  );
}
